[versions]
kotlin = "2.2.21"
agp = "8.12.3"
core = "1.5.0"
kotlinxIoCore = "0.8.0"
kotlinxMetadataJvm = "0.9.0"
multibase = "1.2.2"
bignum = "0.3.10"
jose = "9.31"
kotlinpoet = "2.2.0"
kotlincryptoRandom = "0.6.0"
testballoon = "0.7.1-K2.2.21"
testballoonAddons = "0.5.0"
asp = "20251114"
classgraph = "4.8.184"
cidre = "0.3.1"
urikmp = "0.0.20"



[libraries]
bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIoCore" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }
jose = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "jose" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
multibase = { module = "at.asitplus:multibase", version.ref = "multibase" }
securerandom = { module = "org.kotlincrypto.random:crypto-rand", version.ref = "kotlincryptoRandom" }
asp = { module = "at.asitplus.gradle:k2", version.ref = "asp" }
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }
cidre = { module = "at.asitplus:cidre", version.ref = "cidre"}
urikmp = {module = "com.eygraber:uri-kmp", version.ref = "urikmp"}

#for build logic conventions plugin, as it needs the artefact, not the plugin ID
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }
